page_manager_content_type.page.*:
  type: config_entity
  label: 'Content type page'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    entity_type:
      type: string
      label: 'Entity type'
    entity_bundle:
      type: string
      label: 'Entity bundle'
    enity_view_mode:
      type: string
      label: 'View mode'
    label:
      type: label
      label: 'Label'
    use_admin_theme:
      type: boolean
      label: 'Whether the page is displayed using the admin theme or not'
    display_variants:
      type: sequence
      label: 'Display variants'
      sequence:
        - type: display_variant.plugin.[id]
          label: 'Display variant'
    access_logic:
      type: string
      label: 'Access logic'
    access_conditions:
      type: sequence
      label: 'Access Conditions'
      sequence:
        - type: condition.plugin.[id]
          label: 'Access Condition'
    static_context:
      type: sequence
      label: Static context list
      sequence:
        - type: mapping
          label: 'Static context'
          mapping:
            label:
              type: label
              label: 'Label of the context'
            type:
              type: string
              label: 'Context type'
            value:
              type: string
              label: 'Context value'

page_manager_content_type.block_plugin.*:
  type: block.settings.[id]
  mapping:
    region:
      type: string
      label: 'Region'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
      label: 'UUID'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        - type: string
