<?php

/**
 * @file
 * Contains \Drupal\page_manager\Controller\PageManagerController.
 */

namespace Drupal\page_manager_content_type\Controller;

use Drupal\Component\Plugin\PluginManagerInterface;
use Drupal\Core\Block\BlockManagerInterface;
use Drupal\Core\Controller\ControllerBase;
use Drupal\Core\Plugin\Context\ContextHandlerInterface;
use Drupal\Core\Url;
use Drupal\page_manager\Form\AjaxFormTrait;
use Drupal\page_manager\PageInterface;
use Drupal\page_manager\Controller\PageManagerController;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Request;

/**
 * Provides route controllers for Page Manager.
 */
class PageContentTypeController extends PageManagerController {


  public function editPageTitle(PageInterface $page = NULL) {
//    return parent::editPageTitle($page); // TODO: Change the autogenerated stub
    return 'test';
  }


}
